/**
 * @file ccsds_cfdp_config.h
 * @brief CCSDS CFDP compile-time limits.
 */

#ifndef CCSDS_CFDP_CONFIG_H
#define CCSDS_CFDP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef CONFIG_CCSDS_CFDP_MAX_ENTITY_ID_LEN
#define CONFIG_CCSDS_CFDP_MAX_ENTITY_ID_LEN 4
#endif

#ifndef CONFIG_CCSDS_CFDP_MAX_TRANS_SEQ_LEN
#define CONFIG_CCSDS_CFDP_MAX_TRANS_SEQ_LEN 4
#endif

#ifndef CONFIG_CCSDS_CFDP_MAX_FILENAME_LEN
#define CONFIG_CCSDS_CFDP_MAX_FILENAME_LEN 64
#endif

#ifndef CONFIG_CCSDS_CFDP_MAX_PDU_SIZE
#define CONFIG_CCSDS_CFDP_MAX_PDU_SIZE 512
#endif

#ifndef CONFIG_CCSDS_CFDP_MAX_SEGMENT_SIZE
#define CONFIG_CCSDS_CFDP_MAX_SEGMENT_SIZE 384
#endif

#ifndef CONFIG_CCSDS_CFDP_MAX_NAK_RANGES
#define CONFIG_CCSDS_CFDP_MAX_NAK_RANGES 4
#endif

#ifndef CONFIG_CCSDS_CFDP_MAX_NAK_ROUNDS
#define CONFIG_CCSDS_CFDP_MAX_NAK_ROUNDS 4
#endif

#ifndef CONFIG_CCSDS_CFDP_RETRY_INTERVAL_MS
#define CONFIG_CCSDS_CFDP_RETRY_INTERVAL_MS 1000
#endif

#define CCSDS_CFDP_VERSION_1              1u
#define CCSDS_CFDP_MAX_ENTITY_ID_LEN      CONFIG_CCSDS_CFDP_MAX_ENTITY_ID_LEN
#define CCSDS_CFDP_MAX_TRANS_SEQ_LEN      CONFIG_CCSDS_CFDP_MAX_TRANS_SEQ_LEN
#define CCSDS_CFDP_MAX_FILENAME_LEN       CONFIG_CCSDS_CFDP_MAX_FILENAME_LEN
#define CCSDS_CFDP_MAX_PDU_SIZE           CONFIG_CCSDS_CFDP_MAX_PDU_SIZE
#define CCSDS_CFDP_MAX_SEGMENT_SIZE       CONFIG_CCSDS_CFDP_MAX_SEGMENT_SIZE
#define CCSDS_CFDP_MAX_NAK_RANGES         CONFIG_CCSDS_CFDP_MAX_NAK_RANGES
#define CCSDS_CFDP_MAX_NAK_ROUNDS         CONFIG_CCSDS_CFDP_MAX_NAK_ROUNDS
#define CCSDS_CFDP_RETRY_INTERVAL_MS      CONFIG_CCSDS_CFDP_RETRY_INTERVAL_MS
#define CCSDS_CFDP_MAX_ACTIVE_TX          1u
#define CCSDS_CFDP_MAX_ACTIVE_RX          1u

#ifdef __cplusplus
}
#endif

#endif /* CCSDS_CFDP_CONFIG_H */
