/**
 * @file ccsds_cfdp_types.h
 * @brief CCSDS CFDP constants and protocol enums for AkiraOS.
 */

#ifndef AKIRA_CCSDS_CFDP_TYPES_H
#define AKIRA_CCSDS_CFDP_TYPES_H

#include "ccsds_cfdp_config.h"
#include "ccsds_cfdp_status.h"

#ifdef __cplusplus
extern "C" {
#endif

enum ccsds_cfdp_pdu_type {
    CCSDS_CFDP_PDU_TYPE_FILE_DIRECTIVE = 0,
    CCSDS_CFDP_PDU_TYPE_FILE_DATA = 1,
};

enum ccsds_cfdp_direction {
    CCSDS_CFDP_DIRECTION_TOWARD_RECEIVER = 0,
    CCSDS_CFDP_DIRECTION_TOWARD_SENDER = 1,
};

enum ccsds_cfdp_transmission_mode {
    CCSDS_CFDP_TRANSMISSION_MODE_ACKNOWLEDGED = 0,
    CCSDS_CFDP_TRANSMISSION_MODE_UNACKNOWLEDGED = 1,
};

enum ccsds_cfdp_crc_flag {
    CCSDS_CFDP_CRC_NOT_PRESENT = 0,
    CCSDS_CFDP_CRC_PRESENT = 1,
};

enum ccsds_cfdp_file_size_mode {
    CCSDS_CFDP_FILE_SIZE_SMALL = 0,
    CCSDS_CFDP_FILE_SIZE_LARGE = 1,
};

enum ccsds_cfdp_segmentation_control {
    CCSDS_CFDP_SEGMENTATION_RECORD_BOUNDARIES_NOT_PRESERVED = 0,
    CCSDS_CFDP_SEGMENTATION_RECORD_BOUNDARIES_PRESERVED = 1,
};

enum ccsds_cfdp_directive_code {
    CCSDS_CFDP_DIRECTIVE_EOF = 0x04,
    CCSDS_CFDP_DIRECTIVE_FINISHED = 0x05,
    CCSDS_CFDP_DIRECTIVE_ACK = 0x06,
    CCSDS_CFDP_DIRECTIVE_METADATA = 0x07,
    CCSDS_CFDP_DIRECTIVE_NAK = 0x08,
};

enum ccsds_cfdp_condition_code {
    CCSDS_CFDP_CONDITION_NO_ERROR = 0x0,
    CCSDS_CFDP_CONDITION_POSITIVE_ACK_LIMIT_REACHED = 0x1,
    CCSDS_CFDP_CONDITION_KEEP_ALIVE_LIMIT_REACHED = 0x2,
    CCSDS_CFDP_CONDITION_INVALID_TRANSMISSION_MODE = 0x3,
    CCSDS_CFDP_CONDITION_FILESTORE_REJECTION = 0x4,
    CCSDS_CFDP_CONDITION_FILE_CHECKSUM_FAILURE = 0x5,
    CCSDS_CFDP_CONDITION_FILE_SIZE_ERROR = 0x6,
    CCSDS_CFDP_CONDITION_NAK_LIMIT_REACHED = 0x7,
    CCSDS_CFDP_CONDITION_INACTIVITY_DETECTED = 0x8,
    CCSDS_CFDP_CONDITION_INVALID_FILE_STRUCTURE = 0x9,
    CCSDS_CFDP_CONDITION_CHECK_LIMIT_REACHED = 0xA,
    CCSDS_CFDP_CONDITION_UNSUPPORTED_CHECKSUM_TYPE = 0xB,
    CCSDS_CFDP_CONDITION_SUSPEND_REQUEST_RECEIVED = 0xE,
    CCSDS_CFDP_CONDITION_CANCEL_REQUEST_RECEIVED = 0xF,
};

enum ccsds_cfdp_delivery_code {
    CCSDS_CFDP_DELIVERY_CODE_DATA_COMPLETE = 0,
    CCSDS_CFDP_DELIVERY_CODE_DATA_INCOMPLETE = 1,
};

enum ccsds_cfdp_file_status {
    CCSDS_CFDP_FILE_STATUS_DISCARDED_DELIBERATELY = 0,
    CCSDS_CFDP_FILE_STATUS_DISCARDED_FILESTORE_REJECTION = 1,
    CCSDS_CFDP_FILE_STATUS_RETAINED = 2,
    CCSDS_CFDP_FILE_STATUS_UNREPORTED = 3,
};

enum ccsds_cfdp_checksum_type {
    CCSDS_CFDP_CHECKSUM_TYPE_MODULAR = 0,
    CCSDS_CFDP_CHECKSUM_TYPE_CRC32C = 2,
    CCSDS_CFDP_CHECKSUM_TYPE_IEEE_802_3_FCS = 3,
    CCSDS_CFDP_CHECKSUM_TYPE_NULL = 15,
};

#ifdef __cplusplus
}
#endif

#endif /* AKIRA_CCSDS_CFDP_TYPES_H */
