/**
 * @file ccsds_cfdp_status.h
 * @brief CCSDS CFDP status codes for the planned AkiraOS subset.
 */

#ifndef AKIRA_CCSDS_CFDP_STATUS_H
#define AKIRA_CCSDS_CFDP_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

enum ccsds_cfdp_status {
    CCSDS_CFDP_STATUS_OK = 0,
    CCSDS_CFDP_STATUS_INVALID_ARGUMENT = 1,
    CCSDS_CFDP_STATUS_BUFFER_TOO_SMALL = 2,
    CCSDS_CFDP_STATUS_MALFORMED_PDU = 3,
    CCSDS_CFDP_STATUS_UNSUPPORTED = 4,
    CCSDS_CFDP_STATUS_UNSUPPORTED_CHECKSUM = 5,
    CCSDS_CFDP_STATUS_INVALID_TRANSMISSION_MODE = 6,
    CCSDS_CFDP_STATUS_CHECKSUM_FAILURE = 7,
    CCSDS_CFDP_STATUS_FILE_SIZE_ERROR = 8,
    CCSDS_CFDP_STATUS_INACTIVITY_DETECTED = 9,
    CCSDS_CFDP_STATUS_NAK_LIMIT_REACHED = 10,
    CCSDS_CFDP_STATUS_CANCEL_REQUEST = 11,
    CCSDS_CFDP_STATUS_FILESTORE_REJECTION = 12,
    CCSDS_CFDP_STATUS_TRANSACTION_BUSY = 13,
};

#ifdef __cplusplus
}
#endif

#endif /* AKIRA_CCSDS_CFDP_STATUS_H */
